// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.headuck.phonenumbers;

public class Phonemetadata {

   /*{

     // optional string national_number_pattern = 2;
     public String nationalNumberPattern = null;

     // optional string possible_number_pattern = 3;
     public String possibleNumberPattern = null;

   }*/
   public static final class PhoneMetadata {

     // optional .i18n.phonenumbers.String general_desc = 0;
     public String generalDescPossible;

     // optional .i18n.phonenumbers.String general_desc = 1;
     public String generalDesc;

     // optional .i18n.phonenumbers.String fixed_line = 2;
     public String fixedLine;

     // optional .i18n.phonenumbers.String mobile = 3;
     public String mobile;

     // optional .i18n.phonenumbers.String toll_free = 4;
     public String tollFree;

     // optional .i18n.phonenumbers.String premium_rate = 5;
     public String premiumRate;

     // optional .i18n.phonenumbers.String shared_cost = 6;
     public String sharedCost;

     // optional .i18n.phonenumbers.String personal_number = 7;
     public String personalNumber;

     // optional .i18n.phonenumbers.String voip = 8;
     public String voip;

     // optional .i18n.phonenumbers.String pager = 21;
     public String pager;

     // optional .i18n.phonenumbers.String uan = 25;
     public String uan;

     // optional .i18n.phonenumbers.String emergency = 27;
     // public String emergency;

     // optional .i18n.phonenumbers.String voicemail = 28;
     public String voicemail;

     // optional .i18n.phonenumbers.String short_code = 29;
     // public String shortCode;

     // optional .i18n.phonenumbers.String standard_rate = 30;
     // public String standardRate;

     // optional .i18n.phonenumbers.String carrier_specific = 31;
     // public String carrierSpecific;

     // optional .i18n.phonenumbers.String no_international_dialling = 24;
     // public String noInternationalDialling;


     // required string id = 9;
     public String id;

     // optional int32 country_code = 10;
     public int countryCode;

     // optional string international_prefix = 11;
     public String internationalPrefix;

     // optional bool same_mobile_and_fixed_line_pattern = 18 [default = false];
     public boolean sameMobileAndFixedLinePattern;

     // optional bool main_country_for_code = 22 [default = false];
     public boolean mainCountryForCode;

     // optional string leading_digits = 23;
     public String leadingDigits;

     // optional bool leading_zero_possible = 26 [default = false];
     public boolean leadingZeroPossible;

     // optional bool mobile_number_portable_region = 32 [default = false];
     public boolean mobileNumberPortableRegion;

     // @@protoc_insertion_point(class_scope:i18n.phonenumbers.PhoneMetadata)

     public PhoneMetadata() {
       generalDesc = null;
       fixedLine = null;
       mobile = null;
       tollFree = null;
       premiumRate = null;
       sharedCost = null;
       personalNumber = null;
       voip = null;
       pager = null;
       uan = null;
       // emergency = null;
       voicemail = null;
       // shortCode = null;
       // standardRate = null;
       // carrierSpecific = null;
       // noInternationalDialling = null;

       id = "";
       countryCode = 0;

       internationalPrefix = "";
/*       preferredInternationalPrefix = "";
       nationalPrefix = "";
       preferredExtnPrefix = "";
       nationalPrefixForParsing = "";
       nationalPrefixTransformRule = ""; */
       sameMobileAndFixedLinePattern = false;
       mainCountryForCode = false;
       leadingDigits = "";
       leadingZeroPossible = false;
       mobileNumberPortableRegion = false;

     }
   }
}
